import { useMemo, useState } from 'react'
import { Boxes, CheckCircle2, Cpu, Database, Dice5, Image, Layers3, Play, RotateCcw, SlidersHorizontal, TriangleAlert } from 'lucide-react'

import { AugmentationPreview } from '../components/training/AugmentationPreview'
import { TrainingConsole } from '../components/training/TrainingConsole'
import { StatCard } from '../components/ui/StatCard'

const neutralResolved = { rotation: 0, horizontal_flip: false, vertical_flip: false, brightness: 1, contrast: 1, saturation: 1, hue: 0, grayscale: false, pixelation: 0, blur: 0, noise: 0, noise_seed: 0 }
const operations = ['rotation', 'horizontal_flip', 'vertical_flip', 'brightness', 'contrast', 'saturation', 'hue', 'grayscale', 'pixelation', 'blur', 'noise']
const operationLabels = { rotation: 'Rotation', horizontal_flip: 'Horizontal flip', vertical_flip: 'Vertical flip', brightness: 'Brightness', contrast: 'Contrast', saturation: 'Saturation', hue: 'Hue', grayscale: 'Grayscale', pixelation: 'Pixelation', blur: 'Blur', noise: 'Noise' }
const defaultAugmentation = {
  enabled: true, mode: 'manual', output_strategy: 'on_the_fly', augmentations_per_image: 1,
  manual: { ...neutralResolved }, resolved: { ...neutralResolved },
  random: { min_operations: 1, max_operations: 4, seed: '', auto_randomize: false, enabled_operations: [...operations] },
}

function hashSeed(value) { let hash = 2166136261; for (const char of String(value)) { hash ^= char.charCodeAt(0); hash = Math.imul(hash, 16777619) } return hash >>> 0 }
function seededRandom(seed) { let value = hashSeed(seed); return () => { value += 0x6D2B79F5; let result = value; result = Math.imul(result ^ result >>> 15, result | 1); result ^= result + Math.imul(result ^ result >>> 7, result | 61); return ((result ^ result >>> 14) >>> 0) / 4294967296 } }
function bounded(random, min, max, precision = 2) { return Number((min + random() * (max - min)).toFixed(precision)) }
function resolveRandom(randomConfig) {
  const random = randomConfig.seed === '' ? Math.random : seededRandom(randomConfig.seed)
  const enabled = [...randomConfig.enabled_operations]
  for (let index = enabled.length - 1; index > 0; index -= 1) { const target = Math.floor(random() * (index + 1)); [enabled[index], enabled[target]] = [enabled[target], enabled[index]] }
  const minimum = Math.min(enabled.length, Math.max(0, randomConfig.min_operations))
  const maximum = Math.min(enabled.length, Math.max(minimum, randomConfig.max_operations))
  const count = minimum + Math.floor(random() * (maximum - minimum + 1))
  const selected = enabled.slice(0, count)
  const resolved = { ...neutralResolved }
  selected.forEach((operation) => {
    if (operation === 'rotation') resolved.rotation = [0, 90, 180, -90, -180, 270][Math.floor(random() * 6)]
    else if (operation === 'horizontal_flip' || operation === 'vertical_flip' || operation === 'grayscale') resolved[operation] = random() >= .5
    else if (operation === 'brightness' || operation === 'contrast') resolved[operation] = bounded(random, .7, 1.3)
    else if (operation === 'saturation') resolved.saturation = bounded(random, .6, 1.4)
    else if (operation === 'hue') resolved.hue = bounded(random, -.1, .1)
    else if (operation === 'pixelation') resolved.pixelation = Math.floor(random() * 9)
    else if (operation === 'blur') resolved.blur = bounded(random, 0, 3, 1)
    else if (operation === 'noise') { resolved.noise = Math.round(random() * 16); resolved.noise_seed = Math.floor(random() * 2147483647) }
  })
  return { resolved, selected }
}

function RangeControl({ label, value, min, max, step, disabled, onChange, suffix = '' }) { return <label className="range-control"><span><strong>{label}</strong><output>{value}{suffix}</output></span><input type="range" value={value} min={min} max={max} step={step} disabled={disabled} onChange={(event) => onChange(Number(event.target.value))} /></label> }
function metric(value) { return value == null ? '--' : Number(value).toFixed(4) }

export function Training({ dataset, classes, projectName, training }) {
  const [epochsInput, setEpochsInput] = useState('5'), [imageSize, setImageSize] = useState(640), [batchSize, setBatchSize] = useState(8), [device, setDevice] = useState('auto'), [seed, setSeed] = useState(42)
  const [sampleId, setSampleId] = useState(''), [augmentation, setAugmentation] = useState(defaultAugmentation), [selectedOperations, setSelectedOperations] = useState([])
  const sampleImage = dataset.images.find((image) => image.id === sampleId) || dataset.images[0] || null
  const epochs = Number(epochsInput)
  const epochsValid = /^\d+$/.test(epochsInput) && Number.isInteger(epochs) && epochs >= 1 && epochs <= 500
  const parametersValid = epochsValid && imageSize > 0 && batchSize > 0
  const randomValid = augmentation.random.min_operations >= 0 && augmentation.random.max_operations >= augmentation.random.min_operations
  const canTrain = dataset.stats.annotated_images > 0 && parametersValid && randomValid && !training.any_training_active
  const activeConfig = { enabled: augmentation.enabled, ...(augmentation.mode === 'manual' ? augmentation.manual : augmentation.resolved) }
  const updateRoot = (key, value) => setAugmentation((current) => ({ ...current, [key]: value }))
  const updateManual = (key, value) => setAugmentation((current) => ({ ...current, manual: { ...current.manual, [key]: value } }))
  const updateRandom = (key, value) => setAugmentation((current) => ({ ...current, random: { ...current.random, [key]: value } }))
  const randomize = () => { const result = resolveRandom(augmentation.random); setAugmentation((current) => ({ ...current, resolved: result.resolved })); setSelectedOperations(result.selected) }
  const toggleOperation = (operation) => updateRandom('enabled_operations', augmentation.random.enabled_operations.includes(operation) ? augmentation.random.enabled_operations.filter((item) => item !== operation) : [...augmentation.random.enabled_operations, operation])
  const annotatedPercent = useMemo(() => dataset.stats.total_images ? Math.round(dataset.stats.annotated_images / dataset.stats.total_images * 100) : 0, [dataset.stats])
  const selectSample = (id) => { setSampleId(id); if (augmentation.mode === 'random' && augmentation.random.auto_randomize) randomize() }
  const submitTraining = () => training.start({ epochs, image_size: imageSize, batch_size: batchSize, device, seed, validation_fraction: .2, augmentation: { enabled: augmentation.enabled, mode: augmentation.mode, output_strategy: augmentation.output_strategy, augmentations_per_image: augmentation.augmentations_per_image, manual: augmentation.manual, random: { min_operations: augmentation.random.min_operations, max_operations: augmentation.random.max_operations, seed: augmentation.random.seed || null, enabled_operations: augmentation.random.enabled_operations } } })
  const jobState = training.job?.state || 'IDLE'
  const statusLabel = jobState === 'IDLE' ? 'Not started' : jobState[0] + jobState.slice(1).toLowerCase()
  const statusMessage = training.job?.state === 'FAILED' && training.job.error ? training.job.error : training.running ? `Model ${training.job.model_id} is running locally.` : training.job?.model_id ? `Model version: ${training.job.model_id}` : 'Ready to start a local training job.'

  return <div className="dashboard training-page">
    <div className="page-heading training-heading"><div><span className="eyebrow">LOCAL MODEL PIPELINE</span><h1>Training</h1><p>Configure YOLO training and preview object-detection augmentations.</p></div><span className="local-training-note"><Cpu size={16} /> Training runs locally on your machine</span></div>
    <section className="training-model-card"><div className="model-choice"><span className="model-choice__icon">YOLO</span><div><span className="eyebrow">MODEL</span><h2>YOLO Object Detection</h2><p>Fast, local object-detection training.</p></div><span className="default-pill">DEFAULT</span></div><div className="training-readiness"><span>{annotatedPercent}% labeled</span><small>Only annotated images will be used.</small></div></section>
    <section className="stats-grid stats-grid--five training-stats"><StatCard icon={Database} label="TOTAL IMAGES" value={dataset.stats.total_images} detail="current project" accent="blue" /><StatCard icon={CheckCircle2} label="ANNOTATED" value={dataset.stats.annotated_images} detail="training images" accent="green" /><StatCard icon={Image} label="UNANNOTATED" value={dataset.stats.unannotated_images} detail="excluded initially" accent="amber" /><StatCard icon={Boxes} label="OBJECTS" value={dataset.stats.total_objects} detail="bounding boxes" accent="violet" /><StatCard icon={Layers3} label="CLASSES" value={dataset.stats.classes} detail="labels" accent="blue" /></section>
    <div className="training-columns"><section className="training-card"><div className="training-card__title"><SlidersHorizontal size={17} /><div><h2>Training configuration</h2><p>Core parameters for the local training job.</p></div></div><div className="training-form-grid"><label><span>Epochs</span><input type="number" min="1" max="500" step="1" value={epochsInput} disabled={training.running} aria-invalid={!epochsValid} onChange={(event) => setEpochsInput(event.target.value)} /></label><label><span>Image size</span><input type="number" min="32" value={imageSize} disabled={training.running} onChange={(event) => setImageSize(Number(event.target.value))} /></label><label><span>Batch size</span><input type="number" min="1" value={batchSize} disabled={training.running} onChange={(event) => setBatchSize(Number(event.target.value))} /></label><label><span>Device</span><select value={device} disabled={training.running} onChange={(event) => setDevice(event.target.value)}><option value="auto">Auto</option><option value="cpu">CPU</option><option value="gpu">GPU</option></select></label><label><span>Split seed</span><input type="number" min="0" value={seed} disabled={training.running} onChange={(event) => setSeed(Number(event.target.value))} /></label><label><span>Train / validation</span><input value="80% / 20%" disabled readOnly /></label></div>{!epochsValid && <div className="training-inline-error">Epochs must be a whole number from 1 to 500.</div>}{epochsValid && !parametersValid && <div className="training-inline-error">Image size and batch size must be greater than zero.</div>}</section><section className="training-card status-card"><span className="eyebrow">TRAINING STATUS</span><strong>{statusLabel}</strong><p>{statusMessage}</p><button className="train-button" type="button" disabled={!canTrain} onClick={submitTraining}><Play size={16} /> {training.any_training_active ? 'Training active' : 'Train YOLO'}</button>{training.error && <small>{training.error}</small>}</section></div>
    {training.job?.snapshot_path && <section className="training-card training-results"><div className="training-card__title"><Database size={17}/><div><h2>Dataset split and model details</h2><p>Stable image IDs captured in the immutable training snapshot.</p></div></div>{training.job.warnings?.map((warning) => <div className="training-warning" key={warning}><TriangleAlert size={15}/>{warning}</div>)}<div className="training-details-grid"><div><span>Model</span><strong>{training.job.model_id}</strong></div><div><span>Dataset</span><strong>{training.job.dataset_summary.total_images} images</strong></div><div><span>Train</span><strong>{training.job.dataset_summary.training_images} images</strong></div><div><span>Validation</span><strong>{training.job.dataset_summary.validation_images} images</strong></div><div><span>Classes</span><strong>{training.job.dataset_summary.number_of_classes}</strong></div><div><span>Epochs</span><strong>{training.job.configuration.epochs}</strong></div></div><div className="split-preview"><SplitList title="Training images" images={training.job.train_images}/><SplitList title="Validation images" images={training.job.validation_images}/></div>{training.job.state === 'COMPLETED' && <><h3>Final metrics</h3><div className="training-metrics-grid"><div><span>Training loss</span><strong>{metric(training.job.metrics.loss)}</strong></div><div><span>Validation loss</span><strong>{metric(training.job.metrics.validation_loss)}</strong></div><div><span>Box loss</span><strong>{metric(training.job.metrics.box_loss)}</strong></div><div><span>Class loss</span><strong>{metric(training.job.metrics.class_loss)}</strong></div><div><span>Precision</span><strong>{metric(training.job.metrics.precision)}</strong></div><div><span>Recall</span><strong>{metric(training.job.metrics.recall)}</strong></div><div><span>mAP50</span><strong>{metric(training.job.metrics.map50)}</strong></div><div><span>mAP50-95</span><strong>{metric(training.job.metrics.map50_95)}</strong></div></div><p className="smoke-summary">Validation smoke test: {training.job.validation_images_tested} tested · {training.job.smoke_images_with_predictions} with predictions · {training.job.smoke_total_predictions} predictions</p></>}</section>}
    <section className="training-card augmentation-card"><div className="training-card__title augmentation-title"><SlidersHorizontal size={17} /><div><h2>Data augmentation</h2><p>Preview temporary transformations on one real project image.</p></div><label className="switch-control"><input type="checkbox" checked={augmentation.enabled} onChange={(event) => updateRoot('enabled', event.target.checked)} /><span />Enable augmentation</label></div>
      <div className="augmentation-mode"><strong>AUGMENTATION MODE</strong>{['manual','random'].map((mode) => <label className={augmentation.mode === mode ? 'active' : ''} key={mode}><input type="radio" name="augmentation-mode" checked={augmentation.mode === mode} onChange={() => { updateRoot('mode', mode); if (mode === 'random') randomize() }} />{mode[0].toUpperCase() + mode.slice(1)}</label>)}</div>
      {augmentation.mode === 'manual' ? <div className={`augmentation-controls${augmentation.enabled ? '' : ' disabled'}`}><div className="augmentation-group"><h3>Geometry</h3><label className="training-select"><span>Rotation</span><select value={augmentation.manual.rotation} onChange={(event) => updateManual('rotation', Number(event.target.value))}>{[0,90,180,-90,-180,270].map((value) => <option key={value} value={value}>{value === 0 ? 'None' : `${value}°`}</option>)}</select></label><label className="check-control"><input type="checkbox" checked={augmentation.manual.horizontal_flip} onChange={(event) => updateManual('horizontal_flip', event.target.checked)} />Horizontal flip</label><label className="check-control"><input type="checkbox" checked={augmentation.manual.vertical_flip} onChange={(event) => updateManual('vertical_flip', event.target.checked)} />Vertical flip</label></div><div className="augmentation-group"><h3>Appearance</h3><RangeControl label="Brightness" value={augmentation.manual.brightness} min="0.5" max="1.5" step="0.05" onChange={(value) => updateManual('brightness', value)} /><RangeControl label="Contrast" value={augmentation.manual.contrast} min="0.5" max="1.5" step="0.05" onChange={(value) => updateManual('contrast', value)} /><RangeControl label="Saturation" value={augmentation.manual.saturation} min="0" max="2" step="0.1" onChange={(value) => updateManual('saturation', value)} /><RangeControl label="Hue" value={augmentation.manual.hue} min="-90" max="90" step="5" suffix="°" onChange={(value) => updateManual('hue', value)} /><label className="check-control"><input type="checkbox" checked={augmentation.manual.grayscale} onChange={(event) => updateManual('grayscale', event.target.checked)} />Grayscale</label></div><div className="augmentation-group"><h3>Other</h3><RangeControl label="Pixelation" value={augmentation.manual.pixelation} min="0" max="90" step="5" onChange={(value) => updateManual('pixelation', value)} /><RangeControl label="Gaussian blur" value={augmentation.manual.blur} min="0" max="8" step="0.5" onChange={(value) => updateManual('blur', value)} /><RangeControl label="Noise" value={augmentation.manual.noise} min="0" max="30" step="2" onChange={(value) => updateManual('noise', value)} /><button className="reset-augmentation" type="button" onClick={() => setAugmentation(defaultAugmentation)}><RotateCcw size={14} /> Reset augmentation</button></div></div> : <RandomControls augmentation={augmentation} selected={selectedOperations} updateRandom={updateRandom} toggleOperation={toggleOperation} randomize={randomize} valid={randomValid} />}
      <div className="sample-selector"><label><span>Sample image</span><select value={sampleImage?.id || ''} onChange={(event) => selectSample(event.target.value)} disabled={!dataset.images.length}>{dataset.images.map((image) => <option value={image.id} key={image.id}>{image.filename} · {image.annotation_count} objects</option>)}</select></label><small>{sampleImage ? `${sampleImage.width} × ${sampleImage.height}px` : 'No images in this project'}</small></div><AugmentationPreview image={sampleImage} classes={classes} config={activeConfig} />
      <div className="output-strategy"><h3>Output strategy</h3><label><input type="radio" name="output" checked={augmentation.output_strategy === 'on_the_fly'} onChange={() => updateRoot('output_strategy','on_the_fly')} /><div><strong>On-the-fly augmentation</strong><small>Randomly sample augmentation parameters for training.</small></div></label><label><input type="radio" name="output" checked={augmentation.output_strategy === 'save'} onChange={() => updateRoot('output_strategy','save')} /><div><strong>Save augmented images</strong><small>Future generated files will remain separate from originals.</small></div></label></div>
    </section>
    <TrainingConsole projectName={projectName} stats={dataset.stats} device={device} configuredEpochs={training.job?.configuration?.epochs ?? (epochsValid ? epochs : 5)} state={jobState} logs={training.logs} metrics={training.job?.metrics} onCancel={training.running ? training.cancel : null} />
  </div>
}

function SplitList({ title, images }) {
  return <details><summary>{title}: {images.length}</summary>{images.length ? <ul>{images.map((image) => <li key={image.id}><strong>{image.filename}</strong><code>{image.id}</code></li>)}</ul> : <p>No images in this split.</p>}</details>
}

function RandomControls({ augmentation, selected, updateRandom, toggleOperation, randomize, valid }) {
  const random = augmentation.random
  return <div className={`random-augmentation${augmentation.enabled ? '' : ' disabled'}`}><section><div className="random-heading"><div><h3>RANDOM AUGMENTATION SETTINGS</h3><p>Enabled operations form the pool; each preview uses only a random subset.</p></div><button type="button" onClick={randomize} disabled={!valid || !random.enabled_operations.length}><Dice5 size={15} /> Randomize</button></div><div className="operation-groups">{[['Geometry',['rotation','horizontal_flip','vertical_flip']],['Appearance',['brightness','contrast','saturation','hue','grayscale']],['Other',['pixelation','blur','noise']]].map(([group,items]) => <fieldset key={group}><legend>{group}</legend>{items.map((operation) => <label className="check-control" key={operation}><input type="checkbox" checked={random.enabled_operations.includes(operation)} onChange={() => toggleOperation(operation)} />{operationLabels[operation]}</label>)}</fieldset>)}</div><div className="random-limits"><label><span>Minimum random operations</span><input type="number" min="0" value={random.min_operations} onChange={(event) => updateRandom('min_operations', Number(event.target.value))} /></label><label><span>Maximum random operations</span><input type="number" min="0" value={random.max_operations} onChange={(event) => updateRandom('max_operations', Number(event.target.value))} /></label><label><span>Random seed</span><input type="text" value={random.seed} placeholder="Auto" onChange={(event) => updateRandom('seed', event.target.value)} /></label><label className="check-control auto-randomize"><input type="checkbox" checked={random.auto_randomize} onChange={(event) => updateRandom('auto_randomize', event.target.checked)} />Auto-randomize preview</label></div>{!valid && <div className="training-inline-error">Maximum operations must be greater than or equal to minimum operations.</div>}</section><aside className="random-summary"><span className="eyebrow">RESOLVED AUGMENTATION</span>{operations.map((operation) => { const active = selected.includes(operation); const value = augmentation.resolved[operation]; let display = '—'; if (active) { if (typeof value === 'boolean') display = value ? 'ON' : 'OFF'; else if (operation === 'rotation') display = `${value}°`; else display = value } return <div key={operation}><span>{operationLabels[operation]}</span><strong className={active ? '' : 'inactive'}>{display}</strong></div> })}</aside></div>
}
